Develop
meateam/upload-service pull request #53
Opened 2019-08-28 14:01 UTC by AllKinds

2019-08-28 20:01 UTC, Shahar-Y requested changes
It seems like the changes in this PR are not needed since the normalization was taken care of in api-gateway. 
@omerzamir your opinion?

2019-08-29 06:46 UTC, omerzamir approved these changes

2019-08-29 06:52 UTC, Shahar-Y commented
Agreed to push

2019-08-29 06:52 UTC, Shahar-Y approved these changes

2019-08-29 06:53 UTC, merged